# Site settings
title: Kyshel
description: "Holy"
#url: "https://projectpages.github.io"




# Secondary Parameters
baseurl: "/"
header-img: img/home-bg.jpg
headercolor: "#FFFFFF"
logo: /project-pages/img/logos/Project-Pages-New-Logo-Inverted.png

# Tertiary Parameters
github_username:  kyshel
#project_repository: project-pages
#disqus_shortname: project-pages
#g-analytics: UA-75881392-1
#altmetric: true

# Build settings
gems: [jekyll-paginate]
markdown: kramdown
#highlighter: rouge
#permalink: pretty
paginate: 10
#exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

# Jekyll Settings

defaults:
  -
    scope:
      path: "projects"
      type: "pages"
    values:
      layout: "project"
      header-img: "img/home-bg.jpg"
