### your site title here

title: Kyshel - Blog
# url: "http://kyshel.me"
# baseurl:  # name of the repository
email: a@a.com




# Tracker
google_analytics: UA-86356266-1
duoshuo_username: kyshel

gems: [jekyll-paginate]
paginate: 10
markdown: kramdown
permalink: pretty
highlighter: rouge
include: ['pages']

defaults:
  -
    scope:
      path: "_posts"
      type: "posts"
    values:
      layout: "post"
  -
    scope:
      path: "pages"
      type: "pages"
    values:
      layout: "page"

kramdown:
    syntax_highlighter: rouge
    extensions: ["fenced_code_blocks", "autolink", "tables", "smart"]
sass:
    style: :compressed
    sass_dir: _sass

tags_path: tags



  



