
title: Kyshel
author: Kyshel
url: http://kyshel.me
baseurl:

g-analytics: UA-86356266-1

gems: [jekyll-paginate]
paginate: 10
markdown: kramdown
permalink: pretty
highlighter: rouge
include: ['pages']

defaults:
  -
    scope:
      path: "_posts"
      type: "posts"
    values:
      layout: "post"
